//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatcherModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int IdManager { get; set; }
        public int IdClient { get; set; }
        public int IdGoods { get; set; }
        public int Cost { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual Client Client { get; set; }
    }
}
